#!/bin/bash
username=$(whoami)
echo "Installing id1fs..."
echo "Installing dependencies..."
sudo apt-get install git
sudo apt install python3
sudo apt install python3-pip
pip3 install click
if [ $username = "root" ];
then
    ID1FS_dir="/root/.id1fs"
    Home_dir="/root"
else 
    ID1FS_dir="/home/$username/.id1fs/ID1FS"
    Home_dir="/home/$username"
fi
sudo rm -rvf $ID1FS_dir
sudo mkdir -p $Home_dir
sudo chown $username $Home_dir
mkdir -p $ID1FS_dir
mkdir $ID1FS_dir/backup
mkdir $ID1FS_dir/metadata
mkdir $ID1FS_dir/home
mkdir $ID1FS_dir/downloads
cp -r src $ID1FS_dir
cp -r system $ID1FS_dir
chmod a+x $ID1FS_dir/src/*
chmod a+r $ID1FS_dir/src/*
chmod a+r $ID1FS_dir/system/*
chmod a+w $ID1FS_dir/system/*
python3 setup.py install
cd $Home_dir
cat >> .bashrc << "EOF"
if [ $(whoami) = "root" ]
then
    export ID1FS_dir="/root/.id1fs"
else 
    export ID1FS_dir="/home/$(whoami)/.id1fs"
fi
id1fs_start(){
    $ID1FS_dir/ID1FS/src/id1fs -S && source $ID1FS_dir/ID1FS/system/layout && PATH=$ID1FS_dir/ID1FS/src && source $ID1FS_dir/ID1FS/src/disable_builtin_commands
}
id1fs_stop(){
    $ID1FS_dir/ID1FS/src/id1fs -q && source /etc/environment && source $ID1FS_dir/ID1FS/src/enable_builtin_commands && cd ~ && source ~/.bashrc 
}
EOF
source ~/.bashrc
echo "id1fs installed successfully"