#!/bin/python3
import click
import os
import id1fs_functions as id1fs
import logging
import sys

def list(dirname, count=0):
    if os.path.isdir(dirname):
        for file in os.listdir(dirname):      
            print("--"*count+f"|{file}")
            if os.path.isdir(os.path.join(dirname, file)):
                list(os.path.join(dirname, file), count+1)
    else:
        id1fs.logging_config()
        logging.error(f"{id1fs.get_user()} - arbre command error.")
        print(f"cannot access {dirname} : No such file or directory")


@click.command()
@click.argument("dirname", type=click.STRING, required=0, default=".")
def list_files(dirname):
    """List files in the given directory."""
    if not id1fs.check_status():
        click.echo("filesystem not mounted.")
        sys.exit()
    if not id1fs.check_user():
        click.echo("user not logged in.")
        sys.exit()
    dirname = id1fs.generate_full_path(dirname)
    list(dirname)
    id1fs.logging_config()
    logging.debug(f"{id1fs.get_user()} - arbre command used.")



if __name__ == "__main__":
    list_files()