#!/bin/python3
import os 
import click
import id1fs_functions as id1fs
import sys
import logging

@click.command()
@click.argument("path", type=click.STRING, required=1)
@click.option("-v", "--verbose", is_flag=True, required=0)
def create_dir(path, verbose):
    """Create a directory."""
    path = id1fs.generate_full_path(path)
    root = id1fs.get_root()
    dirname = path.split("/")[-1]
    relative_path = os.path.dirname(path)
    if not id1fs.check_status():
        click.echo("ID1FS is not started yet.")
    if not id1fs.check_user():
        click.echo("No one is connected to id1fs")
    if not os.path.exists(relative_path):
        id1fs.logging_config()
        logging.error(f"{id1fs.get_user()} - {path.replace(root,'')} - create_dir : invalid path.")
        click.echo("this path does not exist")
        sys.exit()
    try:
        os.mkdir(path)
        id1fs.logging_config()
        logging.debug(f"{id1fs.get_user()} - {path.replace(root,'')} folder created.")
        if verbose:
            click.echo(f"Created {path.replace(root, '')}")
    except FileExistsError:
        id1fs.logging_config()
        logging.error(f"{id1fs.get_user()} - {path.replace(root,'')} folder creation already exists.")
        click.echo(f"{path.replace(root,'')} already exists")
    
create_dir()
