#!/bin/python3
import click
import os
import id1fs_functions as id1fs
import sys
import logging

@click.command()
@click.argument("path", type=click.STRING, required=1)
def cat(path):
    """Concatenate FILE(s) to standard output."""
    path = id1fs.generate_full_path(path)
    print(path)
    root = id1fs.get_root()
    if not id1fs.check_status():
        click.echo("The filesystem is not started.")
        sys.exit()
    if not id1fs.check_user():
        click.echo("You are not connected to ID1FS.")
        sys.exit()
    if not os.path.exists(path):
        click.echo(f"cat: {path.replace(root, '')}: No such file or directory")
        sys.exit()
    if os.path.isdir(path):
        click.echo(f"cat: {path}: Is a directory")
        sys.exit()
    if id1fs.check_dir(path) == True:
        click.echo(f"cat: {path.replace(root, '')}: Is a directory")
        sys.exit()
    if path in [f"{root}/system/env.json", f"{root}/system/id1fs_status.json", f"{root}/system/login.json", f"{root}/system/layout", f"{root}/system/metadata.json",f"{root}/system/log"]:
        with open(path, "r") as file:
            click.echo(file.read())
        sys.exit()
    if id1fs.check_access(path, "r") == False:
        id1fs.logging_config()
        logging.error(f"{id1fs.get_user()} - {path.replace(id1fs.get_root(),'')} cat : Permission denied.")
        click.echo(f"cat: {path.replace(root,'')}: Permission denied")
        sys.exit()
    with open(path, "r") as file:
        click.echo(file.read())
    

cat()