#!/bin/python3
import click
import sys
import getpass
import json
import id1fs_functions as id1fs
import logging


@click.command()
@click.argument("user", type=str, required=1)
def login(user):
    """connect to ID1FS."""
    if not id1fs.check_status():
        click.echo("The filesystem is not started.")
        sys.exit()
    if id1fs.check_user():
        click.echo("A user is already connected.")
        sys.exit()
    try:
        with open(id1fs.get_system() + "/login.json", "r")as f:
            users = json.load(f)
    except FileNotFoundError:
        click.echo("No users found.")
        sys.exit()
    except json.decoder.JSONDecodeError:
        click.echo("No users found.")
        sys.exit()
    if user not in users.keys():
        click.echo("This user doesn't exist.\nPlease sign up first.")
        sys.exit()
    password=getpass.getpass("Enter the user password :")
    password=id1fs.hash_string(password)
    if password == users[user].strip():
        id1fs.logging_config()
        logging.info(f"{id1fs.get_user()} - login : {user} is loged in.")
        with open(id1fs.get_system() + "/id1fs_status.json", "r") as f:
            stat = json.load(f)
        stat["connected_user"] = user
        with open(id1fs.get_system() + "/id1fs_status.json", "w")as f:
            json.dump(stat, f)
        with open(id1fs.get_system() + "/layout", "r")as f:
            layout = f.read()
        layout = layout.replace("None", user)
        with open(id1fs.get_system() + "/layout", "w")as f:
            f.write(layout)
    else:
        id1fs.logging_config()
        logging.error(f"{id1fs.get_user()} - login : wrong password.")
        click.echo("Wrong password.")
        sys.exit()


login()