#!/bin/python3
import click

@click.command()
@click.argument('message', nargs=-1)
def my_echo(message):
    """Replica of the echo command."""
    click.echo(' '.join(message))

if __name__ == '__main__':
    my_echo()