#!/bin/python3
import getpass
import hashlib
import click
import random
import sys
import json
import id1fs_functions as id1fs



@click.command()
@click.option("-u", "--username", prompt="the username ", help="Enter the username")
def signup(username):
    """Create a user in ID1FS"""
    if not id1fs.check_status():
        click.echo("The filesystem is not started.")
        sys.exit()
    try:
        with open(id1fs.get_system() + "/login.json", "r")as f:
            users = json.load(f)
    except FileNotFoundError:
        print("No users found.")
        users = {}
    except json.decoder.JSONDecodeError:
        print("No users found.")
        users = {}
    if username in users.keys():
        click.echo(f"This username is already in use.\nTry {username}{random.randint(100, 999)}, {username}{random.randint(100, 999)}{random.randint(100, 999)} or {username}{random.randint(100, 999)}{random.randint(100, 999)}{random.randint(100, 999)}")
        sys.exit()
    while True:
        password = getpass.getpass("Enter the password : ")
        repassword = getpass.getpass("Renter the password : ")
        if password == repassword:
            with open(id1fs.get_system() + "/login.json", "w")as f:
                users[username] = id1fs.hash_string(password)
                json.dump(users, f)
            break
        else:
            click.echo("The passwords don't match.")
            continue


signup()

